name: Hapus Artifact yang Kadaluarsa dalam 24 Jam
# Hapus Artifact Lama Setiap Hari
# Hapus Artifact yang Kadaluarsa Setiap Hari
# Hapus Semua Artifact Setiap Hari
on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  hapus-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Hapus Semua Artifact yang Kadaluarsa
        uses: github/delete-artifacts-action@v1 # actions/delete-artifacts
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          expire-in: 0 # menghapus artifact yang kadaluarsa dalam 24 jam
                       # Set this to 0 to delete all artifacts
